### ISSUE TITLE
events.js link in docs broken

### ISSUE THREAD

**Issue by hansjhoffman** [testing-library/native-testing-library-docs#18]
I see the `src/events.js` link has been updated correctly to `src/lib/events.js` on master but the 4.0.0 docs are still broken. Should there be a hotfix to 4.0.0 (the current stable release)?

**Comment by bcarroll22** [comment]
Yep that would be great, would you be able to make that PR?

**Comment by hansjhoffman** [comment]
Absolutely. I'll push that up this evening after work

**Comment by bcarroll22** [comment]
Closed #19

**Comment by ericbiewener** [comment]
Looks like this is still broken: https://www.native-testing-library.com/docs/api-events
