### ISSUE TITLE
Installation page is outdated

### ISSUE THREAD

**Issue by seancwalsh** [testing-library/native-testing-library-docs#30]
Hi there 👋🏻

I've noticed that the installation page on the documentation website is outdated (https://www.native-testing-library.com/docs/install)

It refers to `jest-expo/jest-preset.json`, where the file is now `jest-expo/jest-preset.js`. I can see that this has been updated in the `install.md` file of this repo.

![image](https://user-images.githubusercontent.com/39013096/77539025-59013080-6ea9-11ea-99ff-a3a1f5311148.png)

Apologies if you already know about this. Cheers!

**Comment by pranjaljately** [comment]
Hi @seancwalsh 

This issue has been fixed: https://github.com/testing-library/native-testing-library-docs/pull/11 and can be closed 👍  @kentcdodds
